import { Medicine, InventoryTransaction, Supplier, Report, AIChatMessage } from '../src/types';

export const DEFAULT_SUPPLIERS: Supplier[] = [
  {
    id: 'sup-1',
    name: 'Pfizer Global Supply',
    contact_person: 'Dr. Robert Vance',
    phone: '+1 (800) 879-3477',
    email: 'orders@pfizersupply.com',
    address: '235 East 42nd Street, New York, NY 10017',
    medicines_supplied: ['med-1', 'med-4'],
    status: 'ACTIVE',
    created_at: '2025-01-15T08:30:00Z'
  },
  {
    id: 'sup-2',
    name: 'Novartis Pharmaceuticals',
    contact_person: 'Sarah Jenkins',
    phone: '+1 (888) 669-6682',
    email: 'logistics.us@novartis.com',
    address: '1 Health Plaza, East Hanover, NJ 07936',
    medicines_supplied: ['med-2', 'med-5'],
    status: 'ACTIVE',
    created_at: '2025-02-10T11:15:00Z'
  },
  {
    id: 'sup-3',
    name: 'GlaxoSmithKline (GSK) Pharma',
    contact_person: 'David Chen',
    phone: '+1 (888) 825-5249',
    email: 'pharma.distribution@gsk.com',
    address: '410 Social Hall Ave, Salt Lake City, UT 84111',
    medicines_supplied: ['med-3', 'med-7', 'med-9'],
    status: 'ACTIVE',
    created_at: '2025-01-20T09:00:00Z'
  },
  {
    id: 'sup-4',
    name: 'Abbott Healthcare Supply',
    contact_person: 'Elena Rostova',
    phone: '+1 (800) 257-9525',
    email: 'supply.chain@abbott.com',
    address: '100 Abbott Park Rd, North Chicago, IL 60064',
    medicines_supplied: ['med-6', 'med-8', 'med-10'],
    status: 'ACTIVE',
    created_at: '2025-03-01T14:20:00Z'
  }
];

export const DEFAULT_MEDICINES: Medicine[] = [
  {
    id: 'med-1',
    name: 'Amoxil 500mg',
    generic_name: 'Amoxicillin Trihydrate',
    brand: 'Amoxil',
    category: 'Antibiotics',
    dosage_form: 'Capsule',
    strength: '500mg',
    batch_number: 'AMO-8912-A',
    supplier: 'Pfizer Global Supply',
    quantity: 120,
    min_stock_level: 50,
    purchase_price: 4.50,
    selling_price: 8.99,
    manufacturing_date: '2023-06-10',
    // Expired 12 days ago to demonstrate Expiry Alert & AI Disposal warning!
    expiry_date: new Date(Date.now() - 12 * 86400000).toISOString().split('T')[0],
    storage_location: 'Shelf A-01 (Controlled Room Temp)',
    qr_code: JSON.stringify({ app: 'PharmaStockAI', id: 'med-1', name: 'Amoxil 500mg', batch: 'AMO-8912-A', exp: 'EXPIRED' }),
    notes: 'Broad-spectrum penicillin antibiotic. Requires cool dry storage.',
    created_at: '2025-01-10T10:00:00Z',
    updated_at: '2026-07-01T12:00:00Z'
  },
  {
    id: 'med-2',
    name: 'Lisinopril 10mg',
    generic_name: 'Lisinopril Dihydrate',
    brand: 'Zestril',
    category: 'Cardiovascular',
    dosage_form: 'Tablet',
    strength: '10mg',
    batch_number: 'LIS-4421-B',
    supplier: 'Novartis Pharmaceuticals',
    quantity: 340,
    min_stock_level: 100,
    purchase_price: 6.20,
    selling_price: 14.50,
    manufacturing_date: '2024-02-15',
    // Expires in 18 days to demonstrate <30 day critical near-expiry alert!
    expiry_date: new Date(Date.now() + 18 * 86400000).toISOString().split('T')[0],
    storage_location: 'Cabinet C-04',
    qr_code: JSON.stringify({ app: 'PharmaStockAI', id: 'med-2', name: 'Lisinopril 10mg', batch: 'LIS-4421-B' }),
    notes: 'ACE inhibitor used for hypertension. High daily prescription volume.',
    created_at: '2025-02-15T09:30:00Z',
    updated_at: '2026-07-10T14:10:00Z'
  },
  {
    id: 'med-3',
    name: 'Glucophage 500mg',
    generic_name: 'Metformin Hydrochloride',
    brand: 'Glucophage',
    category: 'Antidiabetic',
    dosage_form: 'Tablet',
    strength: '500mg',
    batch_number: 'MET-7731-C',
    supplier: 'GlaxoSmithKline (GSK) Pharma',
    quantity: 480,
    min_stock_level: 150,
    purchase_price: 3.10,
    selling_price: 7.50,
    manufacturing_date: '2024-05-20',
    // Expires in 52 days to demonstrate <60 day near-expiry alert!
    expiry_date: new Date(Date.now() + 52 * 86400000).toISOString().split('T')[0],
    storage_location: 'Shelf B-02',
    qr_code: JSON.stringify({ app: 'PharmaStockAI', id: 'med-3', name: 'Glucophage 500mg', batch: 'MET-7731-C' }),
    notes: 'First-line medication for the treatment of type 2 diabetes.',
    created_at: '2025-01-25T11:00:00Z',
    updated_at: '2026-07-15T16:20:00Z'
  },
  {
    id: 'med-4',
    name: 'Lipitor 20mg',
    generic_name: 'Atorvastatin Calcium',
    brand: 'Lipitor',
    category: 'Cardiovascular',
    dosage_form: 'Tablet',
    strength: '20mg',
    batch_number: 'LIP-9021-X',
    supplier: 'Pfizer Global Supply',
    quantity: 620,
    min_stock_level: 200,
    purchase_price: 12.00,
    selling_price: 24.99,
    manufacturing_date: '2024-11-01',
    // Expires in 85 days to demonstrate <90 day near-expiry alert!
    expiry_date: new Date(Date.now() + 85 * 86400000).toISOString().split('T')[0],
    storage_location: 'Cabinet C-01',
    qr_code: JSON.stringify({ app: 'PharmaStockAI', id: 'med-4', name: 'Lipitor 20mg', batch: 'LIP-9021-X' }),
    notes: 'Statin medication used to prevent cardiovascular disease.',
    created_at: '2025-03-05T15:45:00Z',
    updated_at: '2026-07-20T09:15:00Z'
  },
  {
    id: 'med-5',
    name: 'Zithromax 250mg',
    generic_name: 'Azithromycin Dihydrate',
    brand: 'Zithromax',
    category: 'Antibiotics',
    dosage_form: 'Tablet',
    strength: '250mg',
    batch_number: 'AZI-1102-Z',
    supplier: 'Novartis Pharmaceuticals',
    // Out of stock (0) to demonstrate Out of Stock alert and urgent reorder recommendation!
    quantity: 0,
    min_stock_level: 40,
    purchase_price: 8.50,
    selling_price: 18.00,
    manufacturing_date: '2024-08-10',
    expiry_date: new Date(Date.now() + 380 * 86400000).toISOString().split('T')[0],
    storage_location: 'Shelf A-05',
    qr_code: JSON.stringify({ app: 'PharmaStockAI', id: 'med-5', name: 'Zithromax 250mg', batch: 'AZI-1102-Z' }),
    notes: 'Macrolide antibiotic used for respiratory and dermal infections. URGENT REORDER NEEDED.',
    created_at: '2025-04-12T10:30:00Z',
    updated_at: '2026-07-24T18:00:00Z'
  },
  {
    id: 'med-6',
    name: 'Lantus SoloStar 100IU/ml',
    generic_name: 'Insulin Glargine',
    brand: 'Lantus',
    category: 'Antidiabetic',
    dosage_form: 'Injection',
    strength: '100IU/ml (3ml Pen)',
    batch_number: 'LAN-3309-P',
    supplier: 'Abbott Healthcare Supply',
    // Low stock (12 units vs min 25) to demonstrate Low Stock alert!
    quantity: 12,
    min_stock_level: 25,
    purchase_price: 45.00,
    selling_price: 78.50,
    manufacturing_date: '2025-01-10',
    expiry_date: new Date(Date.now() + 290 * 86400000).toISOString().split('T')[0],
    storage_location: 'Refrigerator R-02 (2°C - 8°C)',
    qr_code: JSON.stringify({ app: 'PharmaStockAI', id: 'med-6', name: 'Lantus SoloStar', batch: 'LAN-3309-P' }),
    notes: 'Long-acting insulin. Must be kept refrigerated between 2°C and 8°C.',
    created_at: '2025-03-20T12:00:00Z',
    updated_at: '2026-07-22T11:45:00Z'
  },
  {
    id: 'med-7',
    name: 'Ventolin HFA 100mcg',
    generic_name: 'Salbutamol Sulfate (Albuterol)',
    brand: 'Ventolin',
    category: 'Respiratory',
    dosage_form: 'Inhaler',
    strength: '100mcg/dose (200 actuations)',
    batch_number: 'VEN-5541-H',
    supplier: 'GlaxoSmithKline (GSK) Pharma',
    quantity: 85,
    min_stock_level: 30,
    purchase_price: 15.00,
    selling_price: 29.99,
    manufacturing_date: '2024-10-05',
    expiry_date: new Date(Date.now() + 420 * 86400000).toISOString().split('T')[0],
    storage_location: 'Shelf D-01',
    qr_code: JSON.stringify({ app: 'PharmaStockAI', id: 'med-7', name: 'Ventolin HFA', batch: 'VEN-5541-H' }),
    notes: 'Quick-relief bronchodilator for asthma and COPD acute bronchospasm.',
    created_at: '2025-02-01T14:00:00Z',
    updated_at: '2026-07-18T10:00:00Z'
  },
  {
    id: 'med-8',
    name: 'Prilosec 20mg',
    generic_name: 'Omeprazole Magnesium',
    brand: 'Prilosec',
    category: 'Gastrointestinal',
    dosage_form: 'Capsule',
    strength: '20mg',
    batch_number: 'PRI-6610-M',
    supplier: 'Abbott Healthcare Supply',
    quantity: 210,
    min_stock_level: 60,
    purchase_price: 5.80,
    selling_price: 12.50,
    manufacturing_date: '2024-09-12',
    expiry_date: new Date(Date.now() + 510 * 86400000).toISOString().split('T')[0],
    storage_location: 'Shelf B-05',
    qr_code: JSON.stringify({ app: 'PharmaStockAI', id: 'med-8', name: 'Prilosec 20mg', batch: 'PRI-6610-M' }),
    notes: 'Proton-pump inhibitor used in the treatment of gastroesophageal reflux disease.',
    created_at: '2025-01-30T16:20:00Z',
    updated_at: '2026-07-15T09:00:00Z'
  },
  {
    id: 'med-9',
    name: 'Panadol Extra 500mg/65mg',
    generic_name: 'Paracetamol + Caffeine',
    brand: 'Panadol',
    category: 'Analgesics',
    dosage_form: 'Tablet',
    strength: '500mg/65mg',
    batch_number: 'PAN-2024-T',
    supplier: 'GlaxoSmithKline (GSK) Pharma',
    quantity: 850,
    min_stock_level: 200,
    purchase_price: 2.20,
    selling_price: 5.50,
    manufacturing_date: '2025-02-01',
    expiry_date: new Date(Date.now() + 680 * 86400000).toISOString().split('T')[0],
    storage_location: 'Front Display Shelf F-01',
    qr_code: JSON.stringify({ app: 'PharmaStockAI', id: 'med-9', name: 'Panadol Extra', batch: 'PAN-2024-T' }),
    notes: 'Over-the-counter analgesic and antipyretic. Fast moving consumer product.',
    created_at: '2025-03-10T08:00:00Z',
    updated_at: '2026-07-25T14:30:00Z'
  },
  {
    id: 'med-10',
    name: 'Zyrtec 10mg',
    generic_name: 'Cetirizine Dihydrochloride',
    brand: 'Zyrtec',
    category: 'Antihistamines',
    dosage_form: 'Tablet',
    strength: '10mg',
    batch_number: 'ZYR-8891-C',
    supplier: 'Abbott Healthcare Supply',
    quantity: 310,
    min_stock_level: 80,
    purchase_price: 3.90,
    selling_price: 9.99,
    manufacturing_date: '2024-12-15',
    expiry_date: new Date(Date.now() + 450 * 86400000).toISOString().split('T')[0],
    storage_location: 'Shelf C-03',
    qr_code: JSON.stringify({ app: 'PharmaStockAI', id: 'med-10', name: 'Zyrtec 10mg', batch: 'ZYR-8891-C' }),
    notes: 'Second-generation antihistamine used for relief of seasonal allergic rhinitis.',
    created_at: '2025-02-25T13:10:00Z',
    updated_at: '2026-07-12T11:20:00Z'
  }
];

export const DEFAULT_TRANSACTIONS: InventoryTransaction[] = [
  {
    id: 'tx-1',
    medicine_id: 'med-9',
    medicine_name: 'Panadol Extra 500mg/65mg',
    batch_number: 'PAN-2024-T',
    transaction_type: 'STOCK_IN',
    reason: 'Purchase',
    quantity: 500,
    previous_quantity: 350,
    new_quantity: 850,
    timestamp: new Date(Date.now() - 3 * 3600000).toISOString(),
    notes: 'Restock order #PO-9821 from GSK Pharma.',
    operator: 'Pharm. Alex Vance'
  },
  {
    id: 'tx-2',
    medicine_id: 'med-5',
    medicine_name: 'Zithromax 250mg',
    batch_number: 'AZI-1102-Z',
    transaction_type: 'STOCK_OUT',
    reason: 'Dispensing',
    quantity: 15,
    previous_quantity: 15,
    new_quantity: 0,
    timestamp: new Date(Date.now() - 14 * 3600000).toISOString(),
    notes: 'Dispensed to Ward 4B Respiratory Unit. Stock reached zero.',
    operator: 'Pharm. Elena Vance'
  },
  {
    id: 'tx-3',
    medicine_id: 'med-6',
    medicine_name: 'Lantus SoloStar 100IU/ml',
    batch_number: 'LAN-3309-P',
    transaction_type: 'STOCK_OUT',
    reason: 'Sale',
    quantity: 6,
    previous_quantity: 18,
    new_quantity: 12,
    timestamp: new Date(Date.now() - 28 * 3600000).toISOString(),
    notes: 'Prescription sale #RX-44192. Temperature verification complete.',
    operator: 'Pharm. Alex Vance'
  },
  {
    id: 'tx-4',
    medicine_id: 'med-1',
    medicine_name: 'Amoxil 500mg',
    batch_number: 'AMO-8912-A',
    transaction_type: 'ADJUSTMENT',
    reason: 'Expired',
    quantity: 20,
    previous_quantity: 140,
    new_quantity: 120,
    timestamp: new Date(Date.now() - 48 * 3600000).toISOString(),
    notes: 'Audit audit identified expired blister packs from lot A. Marked for quarantine.',
    operator: 'Dr. Marcus Thorne'
  },
  {
    id: 'tx-5',
    medicine_id: 'med-2',
    medicine_name: 'Lisinopril 10mg',
    batch_number: 'LIS-4421-B',
    transaction_type: 'STOCK_IN',
    reason: 'Purchase',
    quantity: 200,
    previous_quantity: 140,
    new_quantity: 340,
    timestamp: new Date(Date.now() - 72 * 3600000).toISOString(),
    notes: 'Consignment delivery from Novartis.',
    operator: 'Pharm. Alex Vance'
  }
];

export const DEFAULT_CHAT_HISTORY: AIChatMessage[] = [
  {
    id: 'msg-1',
    role: 'assistant',
    content: "Welcome to PharmaStock AI! I am your professional AI pharmacy inventory assistant powered by Google Gemini. I continuously monitor your stock levels, batch numbers, and expiry timelines.\n\nCurrently, I have identified **1 expired medicine** (Amoxil 500mg) that requires quarantine and **1 out-of-stock item** (Zithromax 250mg). How can I assist with your inventory today?",
    timestamp: new Date(Date.now() - 86400000).toISOString(),
    metadata: {
      recommendationType: 'AUDIT',
      suggestedActions: [
        { label: 'View Expired Medicines', action: 'FILTER_EXPIRED' },
        { label: 'Generate Reorder List', action: 'VIEW_REORDER' },
        { label: 'Analyze Expiry Timeline', action: 'VIEW_EXPIRY_ANALYTICS' }
      ]
    }
  }
];

export const DEFAULT_REPORTS: Report[] = [
  {
    id: 'rep-101',
    title: 'Monthly Comprehensive Inventory Audit - July 2026',
    report_type: 'INVENTORY',
    generated_by: 'PharmaStock AI Engine',
    file_format: 'PDF',
    record_count: 10,
    summary: 'Total valuation assessed at $11,365.10 across 10 active pharmaceutical lines. Found 1 expired batch and 1 stockout.',
    created_at: new Date(Date.now() - 86400000 * 2).toISOString()
  },
  {
    id: 'rep-102',
    title: 'Critical Expiry & Quarantine Risk Assessment',
    report_type: 'EXPIRY',
    generated_by: 'Dr. Marcus Thorne',
    file_format: 'EXCEL',
    record_count: 4,
    summary: 'Identified 1 expired item (Amoxil 500mg, 120 units) and 3 near-expiry items within 90 days totaling $13,446 in risk value.',
    created_at: new Date(Date.now() - 86400000 * 4).toISOString()
  },
  {
    id: 'rep-103',
    title: 'Urgent Replenishment & Low Stock Report',
    report_type: 'LOW_STOCK',
    generated_by: 'PharmaStock AI Engine',
    file_format: 'CSV',
    record_count: 2,
    summary: 'Zithromax 250mg is completely out of stock (0 units). Lantus SoloStar is at 12 units (below minimum threshold of 25). Immediate reorder recommended.',
    created_at: new Date(Date.now() - 86400000 * 5).toISOString()
  }
];
